# Generated by Django 5.0.6 on 2024-07-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_paid_amount_student_paid_lessons'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='lesson_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
