# Generated by Django 5.0.6 on 2024-09-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_lesson_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
