version: '4.34'

services:
  web:
    build: .
    command: daphne -b 0.0.0.0 -p 8080 starlingua.asgi:application
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SECRET_KEY: django-insecure-q+wlzxy&13#u+tto@s@toq8k_(k_v^aov2@kotp(9rv2*j6cw5
      EMAIL_HOST: smtp.gmail.com
      EMAIL_PORT: 587
      EMAIL_HOST_USER: STARLINGUA.eu@gmail.com
      EMAIL_HOST_PASSWORD: smmfsarusgkblruh
      LIQPAY_PRIVATE_KEY: TupFRCEXeph5WsB6B1tLhF6K4S6h0oPP2jAMcWBX
      LIQPAY_PUBLIC_KEY: i58576198343
      TELEGRAM_BOT_TOKEN: 7767284133:AAEHu2tQqy2raPJc8AdcSfAHtMYIeooQeOs
      DOMAIN_NAME: starlingua.fly.dev
      PORT: 8080
    volumes:
      - .:/app
    networks:
      - app-network

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: 
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
      DATABASE_PORT: 5432
      DATABASE_HOST: 
    ports:
      - "5540:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  bot:
    build: .
    command: python manage.py telegram_bot

    depends_on:
      - web
    environment:
      TELEGRAM_BOT_TOKEN: 7767284133:AAEHu2tQqy2raPJc8AdcSfAHtMYIeooQeOs
      DOMAIN_NAME: starlingua.fly.dev
      PORT: 8443
    ports:
      - "8443:8443"

    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres_data:
