# Generated by Django 5.0.6 on 2024-07-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='conducted_lessons',
            field=models.IntegerField(default=0),
        ),
    ]
