# Generated by Django 5.0.6 on 2024-08-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='time',
            new_name='start_time',
        ),
        migrations.AddField(
            model_name='lesson',
            name='end_time',
            field=models.TimeField(default='00:00'),
        ),
    ]
