# Generated by Django 5.0.6 on 2024-06-14 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalTurnover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_previous_hours', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_previous_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_current_hours', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_current_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_total_hours', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_profit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_school_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_budget_elena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_budget_maria', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_monthly_profit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_monthly_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_salary_elena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_salary_maria', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_hourly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_money_spent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_remaining_hours', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Turnover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_hours', models.DecimalField(decimal_places=2, max_digits=10)),
                ('previous_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_hours', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_hours', models.DecimalField(decimal_places=2, max_digits=10)),
                ('profit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnovers', to='teachers.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salary_teacher', models.DecimalField(decimal_places=2, max_digits=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_calculations', to='students.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_calculations', to='teachers.teacher')),
                ('turnover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnover.turnover')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_profit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('school_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('budget_elena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('budget_maria', models.DecimalField(decimal_places=2, max_digits=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='students.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='teachers.teacher')),
                ('turnover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnover.turnover')),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_profit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monthly_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salary_elena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salary_maria', models.DecimalField(decimal_places=2, max_digits=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='teachers.teacher')),
                ('turnover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnover.turnover')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('money_spent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remaining_hours', models.DecimalField(decimal_places=2, max_digits=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='students.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='teachers.teacher')),
                ('turnover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnover.turnover')),
            ],
        ),
    ]
