# Generated by Django 5.0.6 on 2024-06-23 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnover', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'permissions': [('can_view_turnover', 'Can view turnover'), ('can_edit_turnover', 'Can edit turnover')]},
        ),
        migrations.AlterModelOptions(
            name='salary',
            options={'permissions': [('can_view_turnover', 'Can view turnover'), ('can_edit_turnover', 'Can edit turnover')]},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'permissions': [('can_view_turnover', 'Can view turnover'), ('can_edit_turnover', 'Can edit turnover')]},
        ),
        migrations.AlterModelOptions(
            name='teachercalculation',
            options={'permissions': [('can_view_turnover', 'Can view turnover'), ('can_edit_turnover', 'Can edit turnover')]},
        ),
        migrations.AlterModelOptions(
            name='totalturnover',
            options={'permissions': [('can_view_turnover', 'Can view turnover'), ('can_edit_turnover', 'Can edit turnover')]},
        ),
        migrations.AlterModelOptions(
            name='turnover',
            options={'permissions': [('can_view_turnover', 'Can view turnover'), ('can_edit_turnover', 'Can edit turnover')]},
        ),
    ]
