# Generated by Django 5.0.6 on 2024-06-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnover', '0002_alter_client_options_alter_salary_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachercalculation',
            name='hours_spent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='totalturnover',
            name='total_hours_spent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
