# Generated by Django 5.0.6 on 2024-06-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnover', '0003_teachercalculation_hours_spent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='remaining_money',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='teachercalculation',
            name='budget_teacher',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='totalturnover',
            name='total_budget_teacher',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='totalturnover',
            name='total_remaining_money',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='totalturnover',
            name='total_salary_teacher',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
