# Generated by Django 5.0.6 on 2024-07-24 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnover', '0004_client_remaining_money_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='student',
        ),
        migrations.RemoveField(
            model_name='client',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='student',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='school',
            name='student',
        ),
        migrations.RemoveField(
            model_name='school',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='teachercalculation',
            name='student',
        ),
        migrations.RemoveField(
            model_name='teachercalculation',
            name='teacher',
        ),
    ]
