# Generated by Django 5.0.6 on 2024-07-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnover', '0006_alter_client_hourly_rate_alter_client_money_spent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalturnover',
            name='total_budget_elena',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='totalturnover',
            name='total_budget_maria',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='totalturnover',
            name='total_current_hours',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='totalturnover',
            name='total_current_payment',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='totalturnover',
            name='total_hourly_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='totalturnover',
            name='total_money_spent',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='totalturnover',
            name='total_monthly_budget',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='totalturnover',
            name='total_monthly_profit',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='totalturnover',
            name='total_previous_balance',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='totalturnover',
            name='total_previous_hours',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='totalturnover',
            name='total_profit',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='totalturnover',
            name='total_remaining_hours',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='totalturnover',
            name='total_salary_elena',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='totalturnover',
            name='total_salary_maria',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='totalturnover',
            name='total_school_budget',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='totalturnover',
            name='total_total_hours',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
