# Generated by Django 5.0.6 on 2024-08-05 14:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnover', '0008_alter_client_hourly_rate_alter_client_money_spent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnover',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
